gazebo_ros_control:
  pid_gains:
    panda_joint1: {p: 12000, i: 0, d: 50}
    panda_joint2: {p: 30000, i: 0.02, d: 100}
    panda_joint3: {p: 18000, i: 0.01, d: 50}
    panda_joint4: {p: 18000, i: 0.01, d: 70}
    panda_joint5: {p: 12000, i: 0.01, d: 70}
    panda_joint6: {p: 7000, i: 0.01, d: 50}
    panda_joint7: {p: 2000, i: 0.5, d: 20}
    panda_finger_joint1: {p: 100, i: 0, d: 50}
    panda_finger_joint2: {p: 100, i: 0, d: 50}
