franka:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
  panda_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
  panda_joint7_controller:
     type: position_controllers/JointPositionController
     joint: panda_joint7
